CREATE TABLE [dbo].[EMPLEADOS_LOCALIZACIONES](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[EMPNIT] [varchar](50) NULL,
	[CODEMP] [int] NULL,
	[FECHA] [date] NULL,
	[HORA] [varchar](10) NULL,
	[LATITUD] [float] NULL,
	[LONGITUD] [float] NULL,
 CONSTRAINT [PK_EMPLEADOS_LOCALIZACIONES] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]




ALTER TABLE EMPLEADOS ADD LATITUD FLOAT NULL;
ALTER TABLE EMPLEADOS ADD LONGITUD FLOAT NULL;



CREATE TRIGGER [dbo].[actualizar_gps_empleado]
ON [dbo].[EMPLEADOS_LOCALIZACIONES]
AFTER INSERT
AS
BEGIN
    -- Actualiza TablaB sumando la cantidad insertada a la existencia
    UPDATE B
    SET B.LATITUD= I.LATITUD, B.LONGITUD= I.LONGITUD
    FROM EMPLEADOS B
    INNER JOIN inserted I ON B.CODEMPLEADO = I.CODEMP;
END;
GO

ALTER TABLE [dbo].[EMPLEADOS_LOCALIZACIONES] ENABLE TRIGGER [actualizar_gps_empleado]
GO






CREATE VIEW [dbo].[PG_DATA_VENDEDOR_CLIENTES_PRODUCTOS_PROM]
AS
SELECT        dbo.DOCUMENTOS.EMPNIT, dbo.DOCUMENTOS.ANIO, dbo.DOCUMENTOS.MES, dbo.DOCUMENTOS.CODEMP, dbo.DOCUMENTOS.CODCLIENTE, COUNT(DISTINCT dbo.DOCPRODUCTOS.CODPROD) AS PROUCTOS_CLIE, 
                         COUNT(dbo.DOCPRODUCTOS.CODPROD) AS PRODUCTOS_CONTEO
FROM            dbo.DOCUMENTOS LEFT OUTER JOIN
                         dbo.TIPODOCUMENTOS ON dbo.DOCUMENTOS.CODDOC = dbo.TIPODOCUMENTOS.CODDOC AND dbo.DOCUMENTOS.EMPNIT = dbo.TIPODOCUMENTOS.EMPNIT LEFT OUTER JOIN
                         dbo.DOCPRODUCTOS ON dbo.DOCUMENTOS.CORRELATIVO = dbo.DOCPRODUCTOS.CORRELATIVO AND dbo.DOCUMENTOS.CODDOC = dbo.DOCPRODUCTOS.CODDOC AND 
                         dbo.DOCUMENTOS.EMPNIT = dbo.DOCPRODUCTOS.EMPNIT
WHERE        (dbo.DOCUMENTOS.STATUS <> 'A') AND (dbo.TIPODOCUMENTOS.TIPODOC IN ('FAC', 'FCP', 'FEC', 'FEF', 'FES', 'FPC'))
GROUP BY dbo.DOCUMENTOS.EMPNIT, dbo.DOCUMENTOS.ANIO, dbo.DOCUMENTOS.MES, dbo.DOCUMENTOS.CODCLIENTE, dbo.DOCUMENTOS.CODEMP




CREATE VIEW [dbo].[PG_VENDEDOR_SKUS_POR_TIENDA_DATA]
AS
SELECT        EMPNIT, ANIO, MES, CODEMP, COUNT(CODCLIENTE) AS CLIENTES, SUM(PROUCTOS_CLIE) AS PRODUCTOS
FROM            dbo.PG_DATA_VENDEDOR_CLIENTES_PRODUCTOS_PROM
GROUP BY EMPNIT, ANIO, MES, CODEMP




CREATE VIEW [dbo].[PG_VENDEDOR_SKUS_POR_TIENDA_RESUMEN_VENDEDOR]
AS
SELECT        EMPNIT, ANIO, MES, CODEMP, CLIENTES, PRODUCTOS, CAST(PRODUCTOS AS FLOAT) / CAST(CLIENTES AS FLOAT) AS SKUS
FROM            dbo.PG_VENDEDOR_SKUS_POR_TIENDA_DATA




CREATE VIEW [dbo].[PG_VENDEDOR_SKUS_POR_TIENDA_RESUMEN_SUCURSAL]
AS
SELECT        EMPNIT, ANIO, MES, SUM(CLIENTES) AS CLIENTES, SUM(PRODUCTOS) AS PRODUCTOS, CAST(SUM(PRODUCTOS) AS FLOAT) / CAST(SUM(CLIENTES) AS FLOAT) AS SKUS
FROM            dbo.PG_VENDEDOR_SKUS_POR_TIENDA_DATA
GROUP BY EMPNIT, ANIO, MES



ALTER TABLE MUNICIPIOS ADD LATITUD FLOAT NULL;
ALTER TABLE MUNICIPIOS ADD LONGITUD FLOAT NULL;


CREATE VIEW [dbo].[view_rpt_marcas_cliente_mes_data]
AS
SELECT        TOP (100) PERCENT EMPNIT, MES, ANIO, CODIGO_CLIENTE, CODIGO_MARCA, MARCA, SUM(TOTALUNIDADES * (INV * - 1)) AS TOTALUNIDADES, SUM(TOTALPRECIO * (INV * - 1)) AS TOTALPRECIO
FROM            dbo.view_rpt_general
WHERE        (CODIGO_CLIENTE IS NOT NULL)
GROUP BY CODIGO_CLIENTE, CODIGO_MARCA, MARCA, EMPNIT, MES, ANIO
ORDER BY CODIGO_MARCA


