CREATE TABLE [dbo].[EMPLEADOS_LOCALIZACIONES](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[EMPNIT] [varchar](50) NULL,
	[CODEMP] [int] NULL,
	[FECHA] [date] NULL,
	[HORA] [varchar](10) NULL,
	[LATITUD] [float] NULL,
	[LONGITUD] [float] NULL,
 CONSTRAINT [PK_EMPLEADOS_LOCALIZACIONES] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]




ALTER TABLE EMPLEADOS ADD LATITUD FLOAT NULL;
ALTER TABLE EMPLEADOS ADD LONGITUD FLOAT NULL;



CREATE TRIGGER [dbo].[actualizar_gps_empleado]
ON [dbo].[EMPLEADOS_LOCALIZACIONES]
AFTER INSERT
AS
BEGIN
    -- Actualiza TablaB sumando la cantidad insertada a la existencia
    UPDATE B
    SET B.LATITUD= I.LATITUD, B.LONGITUD= I.LONGITUD
    FROM EMPLEADOS B
    INNER JOIN inserted I ON B.CODEMPLEADO = I.CODEMP;
END;
GO

ALTER TABLE [dbo].[EMPLEADOS_LOCALIZACIONES] ENABLE TRIGGER [actualizar_gps_empleado]
GO

