CREATE TABLE [dbo].[EMPLEADOS_LOCALIZACIONES](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[EMPNIT] [varchar](50) NULL,
	[CODEMP] [int] NULL,
	[FECHA] [date] NULL,
	[HORA] [varchar](10) NULL,
	[LATITUD] [float] NULL,
	[LONGITUD] [float] NULL,
 CONSTRAINT [PK_EMPLEADOS_LOCALIZACIONES] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]




ALTER TABLE EMPLEADOS ADD LATITUD FLOAT NULL;
ALTER TABLE EMPLEADOS ADD LONGITUD FLOAT NULL;



CREATE TRIGGER [dbo].[actualizar_gps_empleado]
ON [dbo].[EMPLEADOS_LOCALIZACIONES]
AFTER INSERT
AS
BEGIN
    -- Actualiza TablaB sumando la cantidad insertada a la existencia
    UPDATE B
    SET B.LATITUD= I.LATITUD, B.LONGITUD= I.LONGITUD, B.HORA=I.HORA, B.FECHA=I.FECHA
    FROM EMPLEADOS B
    INNER JOIN inserted I ON B.CODEMPLEADO = I.CODEMP;
END;
GO

ALTER TABLE [dbo].[EMPLEADOS_LOCALIZACIONES] ENABLE TRIGGER [actualizar_gps_empleado]
GO






CREATE VIEW [dbo].[PG_DATA_VENDEDOR_CLIENTES_PRODUCTOS_PROM]
AS
SELECT        dbo.DOCUMENTOS.EMPNIT, dbo.DOCUMENTOS.ANIO, dbo.DOCUMENTOS.MES, dbo.DOCUMENTOS.CODEMP, dbo.DOCUMENTOS.CODCLIENTE, COUNT(DISTINCT dbo.DOCPRODUCTOS.CODPROD) AS PROUCTOS_CLIE, 
                         COUNT(dbo.DOCPRODUCTOS.CODPROD) AS PRODUCTOS_CONTEO
FROM            dbo.DOCUMENTOS LEFT OUTER JOIN
                         dbo.TIPODOCUMENTOS ON dbo.DOCUMENTOS.CODDOC = dbo.TIPODOCUMENTOS.CODDOC AND dbo.DOCUMENTOS.EMPNIT = dbo.TIPODOCUMENTOS.EMPNIT LEFT OUTER JOIN
                         dbo.DOCPRODUCTOS ON dbo.DOCUMENTOS.CORRELATIVO = dbo.DOCPRODUCTOS.CORRELATIVO AND dbo.DOCUMENTOS.CODDOC = dbo.DOCPRODUCTOS.CODDOC AND 
                         dbo.DOCUMENTOS.EMPNIT = dbo.DOCPRODUCTOS.EMPNIT
WHERE        (dbo.DOCUMENTOS.STATUS <> 'A') AND (dbo.TIPODOCUMENTOS.TIPODOC IN ('FAC', 'FCP', 'FEC', 'FEF', 'FES', 'FPC'))
GROUP BY dbo.DOCUMENTOS.EMPNIT, dbo.DOCUMENTOS.ANIO, dbo.DOCUMENTOS.MES, dbo.DOCUMENTOS.CODCLIENTE, dbo.DOCUMENTOS.CODEMP




CREATE VIEW [dbo].[PG_VENDEDOR_SKUS_POR_TIENDA_DATA]
AS
SELECT        EMPNIT, ANIO, MES, CODEMP, COUNT(CODCLIENTE) AS CLIENTES, SUM(PROUCTOS_CLIE) AS PRODUCTOS
FROM            dbo.PG_DATA_VENDEDOR_CLIENTES_PRODUCTOS_PROM
GROUP BY EMPNIT, ANIO, MES, CODEMP




CREATE VIEW [dbo].[PG_VENDEDOR_SKUS_POR_TIENDA_RESUMEN_VENDEDOR]
AS
SELECT        EMPNIT, ANIO, MES, CODEMP, CLIENTES, PRODUCTOS, CAST(PRODUCTOS AS FLOAT) / CAST(CLIENTES AS FLOAT) AS SKUS
FROM            dbo.PG_VENDEDOR_SKUS_POR_TIENDA_DATA




CREATE VIEW [dbo].[PG_VENDEDOR_SKUS_POR_TIENDA_RESUMEN_SUCURSAL]
AS
SELECT        EMPNIT, ANIO, MES, SUM(CLIENTES) AS CLIENTES, SUM(PRODUCTOS) AS PRODUCTOS, CAST(SUM(PRODUCTOS) AS FLOAT) / CAST(SUM(CLIENTES) AS FLOAT) AS SKUS
FROM            dbo.PG_VENDEDOR_SKUS_POR_TIENDA_DATA
GROUP BY EMPNIT, ANIO, MES



ALTER TABLE MUNICIPIOS ADD LATITUD FLOAT NULL;
ALTER TABLE MUNICIPIOS ADD LONGITUD FLOAT NULL;


CREATE VIEW [dbo].[view_rpt_marcas_cliente_mes_data]
AS
SELECT        TOP (100) PERCENT EMPNIT, MES, ANIO, CODIGO_CLIENTE, CODIGO_MARCA, MARCA, SUM(TOTALUNIDADES * (INV * - 1)) AS TOTALUNIDADES, SUM(TOTALPRECIO * (INV * - 1)) AS TOTALPRECIO
FROM            dbo.view_rpt_general
WHERE        (CODIGO_CLIENTE IS NOT NULL)
GROUP BY CODIGO_CLIENTE, CODIGO_MARCA, MARCA, EMPNIT, MES, ANIO
ORDER BY CODIGO_MARCA




ALTER TABLE EMPLEADOS ADD HORA VARCHAR(5) NULL;
ALTER TABLE EMPLEADOS ADD FECHA DATE NULL;



ALTER TABLE [dbo].[CLIENTES]  WITH CHECK ADD  CONSTRAINT [FK_CLIENTES_DEPARTAMENTOS] FOREIGN KEY([CODDEPTO])
REFERENCES [dbo].[DEPARTAMENTOS] ([CODDEPTO])
GO

ALTER TABLE [dbo].[CLIENTES] CHECK CONSTRAINT [FK_CLIENTES_DEPARTAMENTOS]
GO



ALTER TABLE [dbo].[CLIENTES]  WITH CHECK ADD  CONSTRAINT [FK_CLIENTES_MUNICIPIOS] FOREIGN KEY([CODMUN])
REFERENCES [dbo].[MUNICIPIOS] ([CODMUN])
GO

ALTER TABLE [dbo].[CLIENTES] CHECK CONSTRAINT [FK_CLIENTES_MUNICIPIOS]
GO



ALTER TABLE EMPLEADOS ADD CODRUTA INT NULL;
ALTER TABLE EMPLEADOS ADD CODCATALOGO INT NULL;



CREATE VIEW [dbo].[param_municipio_universo_clientes]
AS
SELECT        dbo.CLIENTES.CODMUN, dbo.MUNICIPIOS.DESMUN, COUNT(dbo.CLIENTES.CODCLIENTE) AS UNIVERSO, dbo.MUNICIPIOS.LATITUD, dbo.MUNICIPIOS.LONGITUD
FROM            dbo.CLIENTES LEFT OUTER JOIN
                         dbo.MUNICIPIOS ON dbo.CLIENTES.CODMUN = dbo.MUNICIPIOS.CODMUN
WHERE        (dbo.CLIENTES.HABILITADO = 'SI')
GROUP BY dbo.CLIENTES.CODMUN, dbo.MUNICIPIOS.DESMUN, dbo.MUNICIPIOS.LATITUD, dbo.MUNICIPIOS.LONGITUD







CREATE VIEW [dbo].[param_municipio_marcas_clientes_data]
AS
SELECT        dbo.DOCUMENTOS.EMPNIT, dbo.DOCUMENTOS.MES, dbo.DOCUMENTOS.ANIO, dbo.MUNICIPIOS.CODMUN, dbo.MUNICIPIOS.DESMUN, dbo.PRODUCTOS.CODMARCA, dbo.MARCAS.DESMARCA, 
                         dbo.DOCUMENTOS.CODCLIENTE
FROM            dbo.MARCAS RIGHT OUTER JOIN
                         dbo.PRODUCTOS ON dbo.MARCAS.CODMARCA = dbo.PRODUCTOS.CODMARCA RIGHT OUTER JOIN
                         dbo.DOCPRODUCTOS ON dbo.PRODUCTOS.CODPROD = dbo.DOCPRODUCTOS.CODPROD RIGHT OUTER JOIN
                         dbo.DOCUMENTOS ON dbo.DOCPRODUCTOS.CORRELATIVO = dbo.DOCUMENTOS.CORRELATIVO AND dbo.DOCPRODUCTOS.CODDOC = dbo.DOCUMENTOS.CODDOC AND 
                         dbo.DOCPRODUCTOS.EMPNIT = dbo.DOCUMENTOS.EMPNIT LEFT OUTER JOIN
                         dbo.MUNICIPIOS RIGHT OUTER JOIN
                         dbo.CLIENTES ON dbo.MUNICIPIOS.CODMUN = dbo.CLIENTES.CODMUN ON dbo.DOCUMENTOS.EMPNIT = dbo.CLIENTES.EMPNIT AND dbo.DOCUMENTOS.CODCLIENTE = dbo.CLIENTES.CODCLIENTE LEFT OUTER JOIN
                         dbo.TIPODOCUMENTOS ON dbo.DOCUMENTOS.CODDOC = dbo.TIPODOCUMENTOS.CODDOC AND dbo.DOCUMENTOS.EMPNIT = dbo.TIPODOCUMENTOS.EMPNIT
WHERE        (dbo.DOCUMENTOS.STATUS <> 'A') AND (dbo.TIPODOCUMENTOS.TIPODOC IN ('FAC', 'FCP', 'FEC', 'FEF', 'FES', 'FPC'))
GROUP BY dbo.DOCUMENTOS.EMPNIT, dbo.DOCUMENTOS.MES, dbo.DOCUMENTOS.ANIO, dbo.DOCUMENTOS.CODCLIENTE, dbo.MUNICIPIOS.CODMUN, dbo.MUNICIPIOS.DESMUN, dbo.PRODUCTOS.CODMARCA, 
                         dbo.MARCAS.DESMARCA
GO

CREATE VIEW [dbo].[param_municipio_marcas_clientes_res]
AS
SELECT        EMPNIT, MES, ANIO, CODMUN, DESMUN, CODMARCA, DESMARCA, COUNT(CODCLIENTE) AS CONTEO
FROM            dbo.param_municipio_marcas_clientes_data
GROUP BY EMPNIT, MES, ANIO, CODMUN, DESMUN, CODMARCA, DESMARCA
GO






CREATE VIEW [dbo].[param_clientes_vendidos_mes_data]
AS
SELECT        dbo.DOCUMENTOS.EMPNIT, dbo.DOCUMENTOS.MES, dbo.DOCUMENTOS.ANIO, dbo.DOCUMENTOS.CODCLIENTE, dbo.MUNICIPIOS.CODMUN, dbo.MUNICIPIOS.DESMUN
FROM            dbo.MUNICIPIOS RIGHT OUTER JOIN
                         dbo.CLIENTES ON dbo.MUNICIPIOS.CODMUN = dbo.CLIENTES.CODMUN RIGHT OUTER JOIN
                         dbo.DOCUMENTOS ON dbo.CLIENTES.EMPNIT = dbo.DOCUMENTOS.EMPNIT AND dbo.CLIENTES.CODCLIENTE = dbo.DOCUMENTOS.CODCLIENTE LEFT OUTER JOIN
                         dbo.TIPODOCUMENTOS ON dbo.DOCUMENTOS.CODDOC = dbo.TIPODOCUMENTOS.CODDOC AND dbo.DOCUMENTOS.EMPNIT = dbo.TIPODOCUMENTOS.EMPNIT
WHERE        (dbo.DOCUMENTOS.STATUS <> 'A') AND (dbo.TIPODOCUMENTOS.TIPODOC IN ('FAC', 'FCP', 'FEC', 'FEF', 'FES', 'FPC'))
GROUP BY dbo.DOCUMENTOS.EMPNIT, dbo.DOCUMENTOS.MES, dbo.DOCUMENTOS.ANIO, dbo.DOCUMENTOS.CODCLIENTE, dbo.MUNICIPIOS.CODMUN, dbo.MUNICIPIOS.DESMUN
GO



CREATE VIEW [dbo].[param_clientes_vendidos_mes_res]
AS
SELECT        EMPNIT, MES, ANIO, COUNT(CODCLIENTE) AS CLIENTES, CODMUN, DESMUN
FROM            dbo.param_clientes_vendidos_mes_data
GROUP BY EMPNIT, MES, ANIO, CODMUN, DESMUN
GO






ALTER TABLE EMPRESAS ADD OBS_SELLOUT VARCHAR(500) NULL;





CREATE TABLE [dbo].[EMPLEADOS_ASISTENCIA](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[EMPNIT] [varchar](50) NULL,
	[ANIO] [int] NULL,
	[MES] [int] NULL,
	[FECHA] [date] NULL,
	[CODEMP] [int] NULL,
	[HORA_INICIO] [varchar](5) NULL,
	[HORA_FIN] [varchar](5) NULL,
	[VISITAS] [int] NULL,
	[NOCOMPRAN] [int] NULL,
	[NOCOMPRARON] [int] NULL,
	[PEDIDOS] [int] NULL,
	[TOTALPRECIO] [float] NULL,
	[OBS] [varchar](500) NULL,
 CONSTRAINT [PK_EMPLEADOS_ASISTENCIA] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]


