
const execute = require('./../connection');
const express = require('express');
const router = express.Router();



router.post("/print_factura", async(req,res)=>{
   
    const { token, sucursal, coddoc,correlativo} = req.body;

    let qry = `
        SELECT  
            EMPRESAS.NOMBRE AS EMPRESA_NOMBRE, 
            EMPRESAS.DIRECCION AS EMPRESA_DIRECCION, 
            CLIENTES.NIT AS CLIENTE_NIT, 
            CLIENTES.NOMBRE AS CLIENTE_NOMBRE, 
            CLIENTES.DIRECCION AS CLIENTE_DIRECCION, 
            CLIENTES.TELEFONO AS CLIENTE_TELEFONO, 
            EMPLEADOS.NOMEMPLEADO AS EMPLEADO_NOMBRE, 
            EMPLEADOS.TELEFONO AS EMPLEADO_TELEFONO,
            DOCUMENTOS.FECHA,
            DOCUMENTOS.OBS, 
            DOCPRODUCTOS.ID, 
            DOCPRODUCTOS.CODPROD, 
            DOCPRODUCTOS.DESPROD,
            PRODUCTOS.DESPROD2, 
            MARCAS.DESMARCA, 
            DOCPRODUCTOS.CODMEDIDA, 
            DOCPRODUCTOS.CANTIDAD, 
            DOCPRODUCTOS.CANTIDADBONIF, 
            DOCPRODUCTOS.EQUIVALE, 
            DOCPRODUCTOS.TOTALUNIDADES, 
            DOCPRODUCTOS.TOTALBONIF, 
            DOCPRODUCTOS.PRECIO,  
            ISNULL(DOCPRODUCTOS.DESCUENTO,0) AS DESCUENTO, 
            DOCPRODUCTOS.TOTALPRECIO, 
            DOCPRODUCTOS.EXENTO, 
            DOCPRODUCTOS.TIPOPROD, 
            DOCPRODUCTOS.TIPOPRECIO, 
            DOCPRODUCTOS.EXISTENCIA
        FROM  DOCUMENTOS LEFT OUTER JOIN
            EMPLEADOS ON DOCUMENTOS.CODEMP = EMPLEADOS.CODEMPLEADO LEFT OUTER JOIN
            EMPRESAS ON DOCUMENTOS.EMPNIT = EMPRESAS.EMPNIT LEFT OUTER JOIN
            CLIENTES ON DOCUMENTOS.CODCLIENTE = CLIENTES.CODCLIENTE LEFT OUTER JOIN
            DOCPRODUCTOS ON DOCUMENTOS.CORRELATIVO = DOCPRODUCTOS.CORRELATIVO AND DOCUMENTOS.CODDOC = DOCPRODUCTOS.CODDOC AND DOCUMENTOS.EMPNIT = DOCPRODUCTOS.EMPNIT LEFT OUTER JOIN
            PRODUCTOS LEFT OUTER JOIN
            MARCAS ON PRODUCTOS.CODMARCA = MARCAS.CODMARCA ON DOCPRODUCTOS.CODPROD = PRODUCTOS.CODPROD
        WHERE  
            (DOCUMENTOS.EMPNIT = '${sucursal}') AND
            (DOCUMENTOS.CODDOC = '${coddoc}') AND
            (DOCUMENTOS.CORRELATIVO = ${correlativo})
        `
    
    execute.QueryToken(res,qry,token);
     
});



module.exports = router;