-- Bitácora de eliminaciones (también se crea automáticamente desde el backend al primer registro)
IF OBJECT_ID('dbo.BITACORA_ELIMINACIONES', 'U') IS NULL
BEGIN
    CREATE TABLE dbo.BITACORA_ELIMINACIONES (
        ID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
        FECHA_HORA DATETIME NOT NULL CONSTRAINT DF_BITACORA_ELIM_FECHA DEFAULT (GETDATE()),
        FECHA AS (CONVERT(date, FECHA_HORA)) PERSISTED,
        HORA AS (CONVERT(time(0), FECHA_HORA)) PERSISTED,
        EMPNIT VARCHAR(50) NULL,
        USUARIO NVARCHAR(120) NOT NULL CONSTRAINT DF_BITACORA_ELIM_USR DEFAULT (N''),
        MODULO NVARCHAR(80) NOT NULL,
        DETALLE NVARCHAR(MAX) NOT NULL
    );
    CREATE INDEX IX_BITACORA_ELIM_FECHA ON dbo.BITACORA_ELIMINACIONES (FECHA_HORA DESC);
    CREATE INDEX IX_BITACORA_ELIM_MODULO ON dbo.BITACORA_ELIMINACIONES (MODULO, FECHA_HORA DESC);
END
