IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name = 'CONCURSOS_OBJETIVOS_PRODUCTOS' AND schema_id = SCHEMA_ID('dbo'))
BEGIN
    CREATE TABLE dbo.CONCURSOS_OBJETIVOS_PRODUCTOS (
        ID INT IDENTITY(1,1) NOT NULL,
        ID_OBJETIVO INT NOT NULL,
        CODPROD VARCHAR(50) NOT NULL,
        CONSTRAINT PK_CONCURSOS_OBJETIVOS_PRODUCTOS PRIMARY KEY CLUSTERED (ID),
        CONSTRAINT UQ_CONCURSOS_OBJ_PROD UNIQUE (ID_OBJETIVO, CODPROD)
    );
    CREATE NONCLUSTERED INDEX IX_CONCURSOS_OBJ_PROD_OBJ
        ON dbo.CONCURSOS_OBJETIVOS_PRODUCTOS (ID_OBJETIVO);
END
