IF NOT EXISTS (SELECT 1 FROM sys.columns WHERE object_id = OBJECT_ID(N'dbo.CONCURSOS') AND name = 'CODMARCA')
BEGIN
    ALTER TABLE dbo.CONCURSOS ADD CODMARCA INT NOT NULL
        CONSTRAINT DF_CONCURSOS_CODMARCA DEFAULT 0;
END

IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name = 'CONCURSOS_PRODUCTOS' AND schema_id = SCHEMA_ID('dbo'))
BEGIN
    CREATE TABLE dbo.CONCURSOS_PRODUCTOS (
        ID INT IDENTITY(1,1) NOT NULL,
        IDCONCURSO INT NOT NULL,
        CODPROD VARCHAR(50) NOT NULL,
        CONSTRAINT PK_CONCURSOS_PRODUCTOS PRIMARY KEY CLUSTERED (ID),
        CONSTRAINT UQ_CONCURSOS_PROD UNIQUE (IDCONCURSO, CODPROD)
    );
    CREATE NONCLUSTERED INDEX IX_CONCURSOS_PROD_CONC
        ON dbo.CONCURSOS_PRODUCTOS (IDCONCURSO);
END
