-- Descuentos adicionales por línea en compras (DOCPRODUCTOS)
IF COL_LENGTH('dbo.DOCPRODUCTOS', 'DESC1') IS NULL
BEGIN
    EXEC('ALTER TABLE dbo.DOCPRODUCTOS ADD DESC1 DECIMAL(18,4) NOT NULL CONSTRAINT DF_DOCPRODUCTOS_DESC1 DEFAULT (0)');
END
IF COL_LENGTH('dbo.DOCPRODUCTOS', 'DESC2') IS NULL
BEGIN
    EXEC('ALTER TABLE dbo.DOCPRODUCTOS ADD DESC2 DECIMAL(18,4) NOT NULL CONSTRAINT DF_DOCPRODUCTOS_DESC2 DEFAULT (0)');
END
IF COL_LENGTH('dbo.DOCPRODUCTOS', 'DESC3') IS NULL
BEGIN
    EXEC('ALTER TABLE dbo.DOCPRODUCTOS ADD DESC3 DECIMAL(18,4) NOT NULL CONSTRAINT DF_DOCPRODUCTOS_DESC3 DEFAULT (0)');
END
